DROP TABLE TEMPO_IBGE ;

CREATE TABLE TEMPO_IBGE (
  COD_TEMPO NUMBER(7),
  DAT_BASE DATE
);


DECLARE
  cod NUMBER(7) := 1 ;
  dia DATE := TO_DATE('2016-01-01', 'YYYY-MM-DD');
  FIM CONSTANT DATE := TO_DATE('2018-12-31', 'YYYY-MM-DD');
BEGIN
  WHILE (dia <= FIM) LOOP
     INSERT INTO TEMPO_IBGE(COD_TEMPO, DAT_BASE) VALUES (cod, dia);
     cod := cod + 1;
     dia := dia + 1;
  END LOOP;
END;

SELECT * FROM TEMPO_IBGE